// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type NodeInstance struct {
	SessionName string
	NodeID      string
	Scope       string
	Status      string
	Sequence    int64
	RecordJson  string
}

type PersistenceSmoke struct {
	ID        int64
	Note      string
	CreatedAt string
}

type Population struct {
	PopulationKey string
	Workflow      string
	Name          string
}

type PopulationMember struct {
	PopulationKey    string
	ResourceID       string
	SessionName      string
	Generation       int64
	AcceptedAt       string
	LastAppearance   string
	LastInbound      string
	Tombstoned       bool
	PendingUp        bool
	LastDecision     string
	ItemJson         string
	LastBlockersJson string
}

type Session struct {
	Name              string
	ParentSessionName sql.NullString
	RootSessionName   sql.NullString
	ResourceID        string
	Alias             string
	Workflow          string
	WorkspaceDirPath  string
	CreatedAt         string
	UpdatedAt         string
	RecordJson        string
}

type TaskDoneWhenJudge struct {
	TaskInstanceID string
	LeafID         string
	Action         string
	Reason         string
	Revision       string
	JudgeSession   string
	JudgeWorkflow  string
	Relation       string
	CreatedAt      string
}

type TaskDoneWhenState struct {
	TaskInstanceID       string
	HeartbeatTicks       int64
	HeartbeatEscalations int64
	LastAction           string
	LastFingerprint      string
	LastReason           string
	LastUnsatisfiedJson  string
	LastBody             string
	EscalatedAt          string
	EscalateReason       string
}

type TaskInstance struct {
	ID            string
	SessionName   string
	InstanceName  string
	TaskID        string
	Scope         string
	Status        string
	Sequence      int64
	Resource      string
	NamedInstance string
	RecordJson    string
}

type UpReservation struct {
	ChildSessionName string
	ParentName       string
	Pid              int64
	ReservedAt       string
}
