// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const countLiveSessionsNamed = `-- name: CountLiveSessionsNamed :one
SELECT COUNT(*) FROM sessions WHERE name = ? AND status <> 'destroyed'
`

func (q *Queries) CountLiveSessionsNamed(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveSessionsNamed, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNodeInstancesForSession = `-- name: DeleteNodeInstancesForSession :exec
DELETE FROM node_instances WHERE session_id = ?
`

func (q *Queries) DeleteNodeInstancesForSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeInstancesForSession, sessionID)
	return err
}

const deletePopulationMembersForPopulation = `-- name: DeletePopulationMembersForPopulation :exec
DELETE FROM population_members WHERE workflow = ? AND name = ?
`

type DeletePopulationMembersForPopulationParams struct {
	Workflow string
	Name     string
}

func (q *Queries) DeletePopulationMembersForPopulation(ctx context.Context, arg DeletePopulationMembersForPopulationParams) error {
	_, err := q.db.ExecContext(ctx, deletePopulationMembersForPopulation, arg.Workflow, arg.Name)
	return err
}

const deleteSessionChannelHealth = `-- name: DeleteSessionChannelHealth :exec
DELETE FROM session_channel_health WHERE session_id = ? AND kind = ?
`

type DeleteSessionChannelHealthParams struct {
	SessionID string
	Kind      string
}

func (q *Queries) DeleteSessionChannelHealth(ctx context.Context, arg DeleteSessionChannelHealthParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionChannelHealth, arg.SessionID, arg.Kind)
	return err
}

const deleteTaskDoneWhenJudgesByInstanceID = `-- name: DeleteTaskDoneWhenJudgesByInstanceID :exec
DELETE FROM task_done_when_judges WHERE task_instance_id = ?
`

func (q *Queries) DeleteTaskDoneWhenJudgesByInstanceID(ctx context.Context, taskInstanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDoneWhenJudgesByInstanceID, taskInstanceID)
	return err
}

const deleteTaskDoneWhenStateByInstanceID = `-- name: DeleteTaskDoneWhenStateByInstanceID :exec
DELETE FROM task_done_when_states WHERE task_instance_id = ?
`

func (q *Queries) DeleteTaskDoneWhenStateByInstanceID(ctx context.Context, taskInstanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDoneWhenStateByInstanceID, taskInstanceID)
	return err
}

const deleteTaskDoneWhenUnsatisfiedItemsByInstanceID = `-- name: DeleteTaskDoneWhenUnsatisfiedItemsByInstanceID :exec
DELETE FROM task_done_when_unsatisfied_items WHERE task_instance_id = ?
`

func (q *Queries) DeleteTaskDoneWhenUnsatisfiedItemsByInstanceID(ctx context.Context, taskInstanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDoneWhenUnsatisfiedItemsByInstanceID, taskInstanceID)
	return err
}

const deleteTaskInstanceByName = `-- name: DeleteTaskInstanceByName :exec
DELETE FROM task_instances WHERE session_id = ? AND instance_name = ?
`

type DeleteTaskInstanceByNameParams struct {
	SessionID    string
	InstanceName string
}

func (q *Queries) DeleteTaskInstanceByName(ctx context.Context, arg DeleteTaskInstanceByNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskInstanceByName, arg.SessionID, arg.InstanceName)
	return err
}

const deleteTaskInstanceLayersByInstanceID = `-- name: DeleteTaskInstanceLayersByInstanceID :exec
DELETE FROM task_instance_layers WHERE task_instance_id = ?
`

func (q *Queries) DeleteTaskInstanceLayersByInstanceID(ctx context.Context, taskInstanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskInstanceLayersByInstanceID, taskInstanceID)
	return err
}

const deleteUpReservation = `-- name: DeleteUpReservation :exec
DELETE FROM up_reservations WHERE child_session_name = ?
`

func (q *Queries) DeleteUpReservation(ctx context.Context, childSessionName string) error {
	_, err := q.db.ExecContext(ctx, deleteUpReservation, childSessionName)
	return err
}

const getEventCursor = `-- name: GetEventCursor :one
SELECT next_sequence FROM event_cursors WHERE session_id = ? AND kind = ?
`

type GetEventCursorParams struct {
	SessionID string
	Kind      string
}

func (q *Queries) GetEventCursor(ctx context.Context, arg GetEventCursorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEventCursor, arg.SessionID, arg.Kind)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, name, status, destroyed_at, parent_session_id, root_session_id,
       resource_id, alias, workflow, workspace_dir,
       population_workflow, population_name, inputs_json,
       health_last_checked_at, health_last_activity_at, health_last_fingerprint,
       health_last_state, health_last_reason, health_last_notified_at, health_notify_count,
       tick_consecutive_unchanged, tick_last_fingerprint, last_tick_at,
       created_at, updated_at
FROM sessions WHERE name = ? AND status <> 'destroyed'
`

func (q *Queries) GetLiveSession(ctx context.Context, name string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getLiveSession, name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.DestroyedAt,
		&i.ParentSessionID,
		&i.RootSessionID,
		&i.ResourceID,
		&i.Alias,
		&i.Workflow,
		&i.WorkspaceDir,
		&i.PopulationWorkflow,
		&i.PopulationName,
		&i.InputsJson,
		&i.HealthLastCheckedAt,
		&i.HealthLastActivityAt,
		&i.HealthLastFingerprint,
		&i.HealthLastState,
		&i.HealthLastReason,
		&i.HealthLastNotifiedAt,
		&i.HealthNotifyCount,
		&i.TickConsecutiveUnchanged,
		&i.TickLastFingerprint,
		&i.LastTickAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPopulation = `-- name: GetPopulation :one

SELECT workflow, name FROM populations WHERE workflow = ? AND name = ?
`

type GetPopulationParams struct {
	Workflow string
	Name     string
}

// Populations
func (q *Queries) GetPopulation(ctx context.Context, arg GetPopulationParams) (Population, error) {
	row := q.db.QueryRowContext(ctx, getPopulation, arg.Workflow, arg.Name)
	var i Population
	err := row.Scan(&i.Workflow, &i.Name)
	return i, err
}

const hasEventCursor = `-- name: HasEventCursor :one
SELECT COUNT(*) FROM event_cursors WHERE session_id = ? AND kind = ?
`

type HasEventCursorParams struct {
	SessionID string
	Kind      string
}

func (q *Queries) HasEventCursor(ctx context.Context, arg HasEventCursorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasEventCursor, arg.SessionID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, session_id, sequence, time, type, source, direction, summary, body, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID           string
	SessionID    string
	Sequence     int64
	Time         string
	Type         string
	Source       string
	Direction    string
	Summary      string
	Body         string
	MetadataJson string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.SessionID,
		arg.Sequence,
		arg.Time,
		arg.Type,
		arg.Source,
		arg.Direction,
		arg.Summary,
		arg.Body,
		arg.MetadataJson,
	)
	return err
}

const insertNodeInstance = `-- name: InsertNodeInstance :exec

INSERT INTO node_instances (
    session_id, node_id, task_id, name, scope, status, sequence, resource,
    inputs_json, outputs_json, state_json, resource_observation_json,
    resource_observed_at, done_when_json, extra_done_when_json, error,
    setup_at, failed_at, cleaned_at, finalized_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeInstanceParams struct {
	SessionID               string
	NodeID                  string
	TaskID                  sql.NullString
	Name                    sql.NullString
	Scope                   string
	Status                  string
	Sequence                int64
	Resource                sql.NullString
	InputsJson              sql.NullString
	OutputsJson             sql.NullString
	StateJson               sql.NullString
	ResourceObservationJson sql.NullString
	ResourceObservedAt      sql.NullString
	DoneWhenJson            sql.NullString
	ExtraDoneWhenJson       sql.NullString
	Error                   sql.NullString
	SetupAt                 sql.NullString
	FailedAt                sql.NullString
	CleanedAt               sql.NullString
	FinalizedAt             sql.NullString
}

// Workflow nodes (static; Session.Nodes entries)
func (q *Queries) InsertNodeInstance(ctx context.Context, arg InsertNodeInstanceParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeInstance,
		arg.SessionID,
		arg.NodeID,
		arg.TaskID,
		arg.Name,
		arg.Scope,
		arg.Status,
		arg.Sequence,
		arg.Resource,
		arg.InputsJson,
		arg.OutputsJson,
		arg.StateJson,
		arg.ResourceObservationJson,
		arg.ResourceObservedAt,
		arg.DoneWhenJson,
		arg.ExtraDoneWhenJson,
		arg.Error,
		arg.SetupAt,
		arg.FailedAt,
		arg.CleanedAt,
		arg.FinalizedAt,
	)
	return err
}

const insertNodeInstanceLayer = `-- name: InsertNodeInstanceLayer :exec
INSERT INTO node_instance_layers (
    session_id, node_id, position, effect_id, status, inputs_json,
    locals_json, outputs_json, env_json, heartbeat_ticks,
    heartbeat_escalations, setup_at, failed_at, cleaned_at, error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeInstanceLayerParams struct {
	SessionID            string
	NodeID               string
	Position             int64
	EffectID             string
	Status               string
	InputsJson           sql.NullString
	LocalsJson           sql.NullString
	OutputsJson          sql.NullString
	EnvJson              sql.NullString
	HeartbeatTicks       sql.NullInt64
	HeartbeatEscalations sql.NullInt64
	SetupAt              sql.NullString
	FailedAt             sql.NullString
	CleanedAt            sql.NullString
	Error                sql.NullString
}

func (q *Queries) InsertNodeInstanceLayer(ctx context.Context, arg InsertNodeInstanceLayerParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeInstanceLayer,
		arg.SessionID,
		arg.NodeID,
		arg.Position,
		arg.EffectID,
		arg.Status,
		arg.InputsJson,
		arg.LocalsJson,
		arg.OutputsJson,
		arg.EnvJson,
		arg.HeartbeatTicks,
		arg.HeartbeatEscalations,
		arg.SetupAt,
		arg.FailedAt,
		arg.CleanedAt,
		arg.Error,
	)
	return err
}

const insertPopulationMember = `-- name: InsertPopulationMember :exec
INSERT INTO population_members (
    workflow, name, resource_id, session_name, generation, accepted_at,
    last_appearance, last_inbound, tombstoned, pending_up,
    decision_kind, decision_reason, item_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPopulationMemberParams struct {
	Workflow       string
	Name           string
	ResourceID     string
	SessionName    sql.NullString
	Generation     int64
	AcceptedAt     sql.NullString
	LastAppearance sql.NullString
	LastInbound    sql.NullString
	Tombstoned     bool
	PendingUp      bool
	DecisionKind   sql.NullString
	DecisionReason sql.NullString
	ItemJson       string
}

func (q *Queries) InsertPopulationMember(ctx context.Context, arg InsertPopulationMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertPopulationMember,
		arg.Workflow,
		arg.Name,
		arg.ResourceID,
		arg.SessionName,
		arg.Generation,
		arg.AcceptedAt,
		arg.LastAppearance,
		arg.LastInbound,
		arg.Tombstoned,
		arg.PendingUp,
		arg.DecisionKind,
		arg.DecisionReason,
		arg.ItemJson,
	)
	return err
}

const insertPopulationMemberBlocker = `-- name: InsertPopulationMemberBlocker :exec
INSERT INTO population_member_blockers (workflow, name, resource_id, position, reason)
VALUES (?, ?, ?, ?, ?)
`

type InsertPopulationMemberBlockerParams struct {
	Workflow   string
	Name       string
	ResourceID string
	Position   int64
	Reason     string
}

func (q *Queries) InsertPopulationMemberBlocker(ctx context.Context, arg InsertPopulationMemberBlockerParams) error {
	_, err := q.db.ExecContext(ctx, insertPopulationMemberBlocker,
		arg.Workflow,
		arg.Name,
		arg.ResourceID,
		arg.Position,
		arg.Reason,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO sessions (
    id, name, status, destroyed_at, parent_session_id, root_session_id,
    resource_id, alias, workflow, workspace_dir,
    population_workflow, population_name, inputs_json,
    health_last_checked_at, health_last_activity_at, health_last_fingerprint,
    health_last_state, health_last_reason, health_last_notified_at, health_notify_count,
    tick_consecutive_unchanged, tick_last_fingerprint, last_tick_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID                       string
	Name                     string
	Status                   string
	DestroyedAt              sql.NullString
	ParentSessionID          sql.NullString
	RootSessionID            sql.NullString
	ResourceID               sql.NullString
	Alias                    sql.NullString
	Workflow                 string
	WorkspaceDir             sql.NullString
	PopulationWorkflow       sql.NullString
	PopulationName           sql.NullString
	InputsJson               sql.NullString
	HealthLastCheckedAt      sql.NullString
	HealthLastActivityAt     sql.NullString
	HealthLastFingerprint    sql.NullString
	HealthLastState          sql.NullString
	HealthLastReason         sql.NullString
	HealthLastNotifiedAt     sql.NullString
	HealthNotifyCount        sql.NullInt64
	TickConsecutiveUnchanged sql.NullInt64
	TickLastFingerprint      sql.NullString
	LastTickAt               sql.NullString
	CreatedAt                string
	UpdatedAt                string
}

// Sessions
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.DestroyedAt,
		arg.ParentSessionID,
		arg.RootSessionID,
		arg.ResourceID,
		arg.Alias,
		arg.Workflow,
		arg.WorkspaceDir,
		arg.PopulationWorkflow,
		arg.PopulationName,
		arg.InputsJson,
		arg.HealthLastCheckedAt,
		arg.HealthLastActivityAt,
		arg.HealthLastFingerprint,
		arg.HealthLastState,
		arg.HealthLastReason,
		arg.HealthLastNotifiedAt,
		arg.HealthNotifyCount,
		arg.TickConsecutiveUnchanged,
		arg.TickLastFingerprint,
		arg.LastTickAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTaskDoneWhenJudge = `-- name: InsertTaskDoneWhenJudge :exec

INSERT INTO task_done_when_judges (
    task_instance_id, leaf_id, action, reason, revision,
    judge_session, judge_workflow, relation, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskDoneWhenJudgeParams struct {
	TaskInstanceID string
	LeafID         string
	Action         string
	Reason         string
	Revision       string
	JudgeSession   string
	JudgeWorkflow  sql.NullString
	Relation       string
	CreatedAt      string
}

// Task done_when judges
func (q *Queries) InsertTaskDoneWhenJudge(ctx context.Context, arg InsertTaskDoneWhenJudgeParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskDoneWhenJudge,
		arg.TaskInstanceID,
		arg.LeafID,
		arg.Action,
		arg.Reason,
		arg.Revision,
		arg.JudgeSession,
		arg.JudgeWorkflow,
		arg.Relation,
		arg.CreatedAt,
	)
	return err
}

const insertTaskDoneWhenState = `-- name: InsertTaskDoneWhenState :exec

INSERT INTO task_done_when_states (
    task_instance_id, heartbeat_ticks, heartbeat_escalations,
    last_action, last_fingerprint, last_reason,
    last_body, escalated_at, escalate_reason
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskDoneWhenStateParams struct {
	TaskInstanceID       string
	HeartbeatTicks       int64
	HeartbeatEscalations int64
	LastAction           sql.NullString
	LastFingerprint      sql.NullString
	LastReason           sql.NullString
	LastBody             sql.NullString
	EscalatedAt          sql.NullString
	EscalateReason       sql.NullString
}

// Task done_when states
func (q *Queries) InsertTaskDoneWhenState(ctx context.Context, arg InsertTaskDoneWhenStateParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskDoneWhenState,
		arg.TaskInstanceID,
		arg.HeartbeatTicks,
		arg.HeartbeatEscalations,
		arg.LastAction,
		arg.LastFingerprint,
		arg.LastReason,
		arg.LastBody,
		arg.EscalatedAt,
		arg.EscalateReason,
	)
	return err
}

const insertTaskDoneWhenUnsatisfiedItem = `-- name: InsertTaskDoneWhenUnsatisfiedItem :exec
INSERT INTO task_done_when_unsatisfied_items (task_instance_id, position, item)
VALUES (?, ?, ?)
`

type InsertTaskDoneWhenUnsatisfiedItemParams struct {
	TaskInstanceID string
	Position       int64
	Item           string
}

func (q *Queries) InsertTaskDoneWhenUnsatisfiedItem(ctx context.Context, arg InsertTaskDoneWhenUnsatisfiedItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskDoneWhenUnsatisfiedItem, arg.TaskInstanceID, arg.Position, arg.Item)
	return err
}

const insertTaskInstanceLayer = `-- name: InsertTaskInstanceLayer :exec
INSERT INTO task_instance_layers (
    task_instance_id, position, effect_id, status, inputs_json, locals_json,
    outputs_json, env_json, heartbeat_ticks, heartbeat_escalations,
    setup_at, failed_at, cleaned_at, error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskInstanceLayerParams struct {
	TaskInstanceID       string
	Position             int64
	EffectID             string
	Status               string
	InputsJson           sql.NullString
	LocalsJson           sql.NullString
	OutputsJson          sql.NullString
	EnvJson              sql.NullString
	HeartbeatTicks       sql.NullInt64
	HeartbeatEscalations sql.NullInt64
	SetupAt              sql.NullString
	FailedAt             sql.NullString
	CleanedAt            sql.NullString
	Error                sql.NullString
}

func (q *Queries) InsertTaskInstanceLayer(ctx context.Context, arg InsertTaskInstanceLayerParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskInstanceLayer,
		arg.TaskInstanceID,
		arg.Position,
		arg.EffectID,
		arg.Status,
		arg.InputsJson,
		arg.LocalsJson,
		arg.OutputsJson,
		arg.EnvJson,
		arg.HeartbeatTicks,
		arg.HeartbeatEscalations,
		arg.SetupAt,
		arg.FailedAt,
		arg.CleanedAt,
		arg.Error,
	)
	return err
}

const latestEventByType = `-- name: LatestEventByType :one
SELECT id, sequence, time, type, source, direction, summary, body, metadata_json
FROM events WHERE session_id = ? AND type = ? ORDER BY sequence DESC LIMIT 1
`

type LatestEventByTypeParams struct {
	SessionID string
	Type      string
}

type LatestEventByTypeRow struct {
	ID           string
	Sequence     int64
	Time         string
	Type         string
	Source       string
	Direction    string
	Summary      string
	Body         string
	MetadataJson string
}

// LatestEventByType backs the status-message reader.
func (q *Queries) LatestEventByType(ctx context.Context, arg LatestEventByTypeParams) (LatestEventByTypeRow, error) {
	row := q.db.QueryRowContext(ctx, latestEventByType, arg.SessionID, arg.Type)
	var i LatestEventByTypeRow
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Time,
		&i.Type,
		&i.Source,
		&i.Direction,
		&i.Summary,
		&i.Body,
		&i.MetadataJson,
	)
	return i, err
}

const listEventsFromBySession = `-- name: ListEventsFromBySession :many
SELECT id, sequence, time, type, source, direction, summary, body, metadata_json
FROM events WHERE session_id = ? AND sequence >= ? ORDER BY sequence
`

type ListEventsFromBySessionParams struct {
	SessionID string
	Sequence  int64
}

type ListEventsFromBySessionRow struct {
	ID           string
	Sequence     int64
	Time         string
	Type         string
	Source       string
	Direction    string
	Summary      string
	Body         string
	MetadataJson string
}

func (q *Queries) ListEventsFromBySession(ctx context.Context, arg ListEventsFromBySessionParams) ([]ListEventsFromBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsFromBySession, arg.SessionID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsFromBySessionRow
	for rows.Next() {
		var i ListEventsFromBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.Time,
			&i.Type,
			&i.Source,
			&i.Direction,
			&i.Summary,
			&i.Body,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEverSessionNames = `-- name: ListEverSessionNames :many
SELECT DISTINCT name FROM sessions ORDER BY name
`

func (q *Queries) ListEverSessionNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEverSessionNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveChildSessionNames = `-- name: ListLiveChildSessionNames :many
SELECT name FROM sessions WHERE parent_session_id = ? AND status <> 'destroyed' ORDER BY name
`

func (q *Queries) ListLiveChildSessionNames(ctx context.Context, parentSessionID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLiveChildSessionNames, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveChildSessionNamesForSessions = `-- name: ListLiveChildSessionNamesForSessions :many
SELECT parent_session_id, name FROM sessions
WHERE parent_session_id IN (/*SLICE:parent_ids*/?) AND status <> 'destroyed'
ORDER BY parent_session_id, name
`

type ListLiveChildSessionNamesForSessionsRow struct {
	ParentSessionID sql.NullString
	Name            string
}

func (q *Queries) ListLiveChildSessionNamesForSessions(ctx context.Context, parentIds []sql.NullString) ([]ListLiveChildSessionNamesForSessionsRow, error) {
	query := listLiveChildSessionNamesForSessions
	var queryParams []interface{}
	if len(parentIds) > 0 {
		for _, v := range parentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", strings.Repeat(",?", len(parentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveChildSessionNamesForSessionsRow
	for rows.Next() {
		var i ListLiveChildSessionNamesForSessionsRow
		if err := rows.Scan(&i.ParentSessionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT id, name, status, destroyed_at, parent_session_id, root_session_id,
       resource_id, alias, workflow, workspace_dir,
       population_workflow, population_name, inputs_json,
       health_last_checked_at, health_last_activity_at, health_last_fingerprint,
       health_last_state, health_last_reason, health_last_notified_at, health_notify_count,
       tick_consecutive_unchanged, tick_last_fingerprint, last_tick_at,
       created_at, updated_at
FROM sessions WHERE status <> 'destroyed' ORDER BY name
`

func (q *Queries) ListLiveSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listLiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.DestroyedAt,
			&i.ParentSessionID,
			&i.RootSessionID,
			&i.ResourceID,
			&i.Alias,
			&i.Workflow,
			&i.WorkspaceDir,
			&i.PopulationWorkflow,
			&i.PopulationName,
			&i.InputsJson,
			&i.HealthLastCheckedAt,
			&i.HealthLastActivityAt,
			&i.HealthLastFingerprint,
			&i.HealthLastState,
			&i.HealthLastReason,
			&i.HealthLastNotifiedAt,
			&i.HealthNotifyCount,
			&i.TickConsecutiveUnchanged,
			&i.TickLastFingerprint,
			&i.LastTickAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByAlias = `-- name: ListLiveSessionsByAlias :many
SELECT id, name, status, destroyed_at, parent_session_id, root_session_id,
       resource_id, alias, workflow, workspace_dir,
       population_workflow, population_name, inputs_json,
       health_last_checked_at, health_last_activity_at, health_last_fingerprint,
       health_last_state, health_last_reason, health_last_notified_at, health_notify_count,
       tick_consecutive_unchanged, tick_last_fingerprint, last_tick_at,
       created_at, updated_at
FROM sessions WHERE alias = ? AND status <> 'destroyed' ORDER BY name
`

func (q *Queries) ListLiveSessionsByAlias(ctx context.Context, alias sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listLiveSessionsByAlias, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.DestroyedAt,
			&i.ParentSessionID,
			&i.RootSessionID,
			&i.ResourceID,
			&i.Alias,
			&i.Workflow,
			&i.WorkspaceDir,
			&i.PopulationWorkflow,
			&i.PopulationName,
			&i.InputsJson,
			&i.HealthLastCheckedAt,
			&i.HealthLastActivityAt,
			&i.HealthLastFingerprint,
			&i.HealthLastState,
			&i.HealthLastReason,
			&i.HealthLastNotifiedAt,
			&i.HealthNotifyCount,
			&i.TickConsecutiveUnchanged,
			&i.TickLastFingerprint,
			&i.LastTickAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceLayers = `-- name: ListNodeInstanceLayers :many
SELECT session_id, node_id, position, effect_id, status, inputs_json,
       locals_json, outputs_json, env_json, heartbeat_ticks,
       heartbeat_escalations, setup_at, failed_at, cleaned_at, error
FROM node_instance_layers WHERE session_id = ? ORDER BY node_id, position
`

func (q *Queries) ListNodeInstanceLayers(ctx context.Context, sessionID string) ([]NodeInstanceLayer, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInstanceLayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeInstanceLayer
	for rows.Next() {
		var i NodeInstanceLayer
		if err := rows.Scan(
			&i.SessionID,
			&i.NodeID,
			&i.Position,
			&i.EffectID,
			&i.Status,
			&i.InputsJson,
			&i.LocalsJson,
			&i.OutputsJson,
			&i.EnvJson,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceLayersForSessions = `-- name: ListNodeInstanceLayersForSessions :many
SELECT session_id, node_id, position, effect_id, status, inputs_json,
       locals_json, outputs_json, env_json, heartbeat_ticks,
       heartbeat_escalations, setup_at, failed_at, cleaned_at, error
FROM node_instance_layers WHERE session_id IN (/*SLICE:session_ids*/?)
ORDER BY session_id, node_id, position
`

func (q *Queries) ListNodeInstanceLayersForSessions(ctx context.Context, sessionIds []string) ([]NodeInstanceLayer, error) {
	query := listNodeInstanceLayersForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeInstanceLayer
	for rows.Next() {
		var i NodeInstanceLayer
		if err := rows.Scan(
			&i.SessionID,
			&i.NodeID,
			&i.Position,
			&i.EffectID,
			&i.Status,
			&i.InputsJson,
			&i.LocalsJson,
			&i.OutputsJson,
			&i.EnvJson,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstances = `-- name: ListNodeInstances :many
SELECT session_id, node_id, task_id, name, scope, status, sequence, resource,
       inputs_json, outputs_json, state_json, resource_observation_json,
       resource_observed_at, done_when_json, extra_done_when_json, error,
       setup_at, failed_at, cleaned_at, finalized_at
FROM node_instances WHERE session_id = ? ORDER BY node_id
`

func (q *Queries) ListNodeInstances(ctx context.Context, sessionID string) ([]NodeInstance, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInstances, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeInstance
	for rows.Next() {
		var i NodeInstance
		if err := rows.Scan(
			&i.SessionID,
			&i.NodeID,
			&i.TaskID,
			&i.Name,
			&i.Scope,
			&i.Status,
			&i.Sequence,
			&i.Resource,
			&i.InputsJson,
			&i.OutputsJson,
			&i.StateJson,
			&i.ResourceObservationJson,
			&i.ResourceObservedAt,
			&i.DoneWhenJson,
			&i.ExtraDoneWhenJson,
			&i.Error,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstancesForSessions = `-- name: ListNodeInstancesForSessions :many
SELECT session_id, node_id, task_id, name, scope, status, sequence, resource,
       inputs_json, outputs_json, state_json, resource_observation_json,
       resource_observed_at, done_when_json, extra_done_when_json, error,
       setup_at, failed_at, cleaned_at, finalized_at
FROM node_instances WHERE session_id IN (/*SLICE:session_ids*/?) ORDER BY session_id, node_id
`

func (q *Queries) ListNodeInstancesForSessions(ctx context.Context, sessionIds []string) ([]NodeInstance, error) {
	query := listNodeInstancesForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeInstance
	for rows.Next() {
		var i NodeInstance
		if err := rows.Scan(
			&i.SessionID,
			&i.NodeID,
			&i.TaskID,
			&i.Name,
			&i.Scope,
			&i.Status,
			&i.Sequence,
			&i.Resource,
			&i.InputsJson,
			&i.OutputsJson,
			&i.StateJson,
			&i.ResourceObservationJson,
			&i.ResourceObservedAt,
			&i.DoneWhenJson,
			&i.ExtraDoneWhenJson,
			&i.Error,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopulationMemberBlockersForPopulation = `-- name: ListPopulationMemberBlockersForPopulation :many
SELECT b.workflow, b.name, b.resource_id, b.position, b.reason
FROM population_member_blockers b
WHERE b.workflow = ? AND b.name = ?
ORDER BY b.resource_id, b.position
`

type ListPopulationMemberBlockersForPopulationParams struct {
	Workflow string
	Name     string
}

func (q *Queries) ListPopulationMemberBlockersForPopulation(ctx context.Context, arg ListPopulationMemberBlockersForPopulationParams) ([]PopulationMemberBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listPopulationMemberBlockersForPopulation, arg.Workflow, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PopulationMemberBlocker
	for rows.Next() {
		var i PopulationMemberBlocker
		if err := rows.Scan(
			&i.Workflow,
			&i.Name,
			&i.ResourceID,
			&i.Position,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopulationMembers = `-- name: ListPopulationMembers :many
SELECT workflow, name, resource_id, session_name, generation, accepted_at,
       last_appearance, last_inbound, tombstoned, pending_up,
       decision_kind, decision_reason, item_json
FROM population_members WHERE workflow = ? AND name = ? ORDER BY resource_id
`

type ListPopulationMembersParams struct {
	Workflow string
	Name     string
}

func (q *Queries) ListPopulationMembers(ctx context.Context, arg ListPopulationMembersParams) ([]PopulationMember, error) {
	rows, err := q.db.QueryContext(ctx, listPopulationMembers, arg.Workflow, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PopulationMember
	for rows.Next() {
		var i PopulationMember
		if err := rows.Scan(
			&i.Workflow,
			&i.Name,
			&i.ResourceID,
			&i.SessionName,
			&i.Generation,
			&i.AcceptedAt,
			&i.LastAppearance,
			&i.LastInbound,
			&i.Tombstoned,
			&i.PendingUp,
			&i.DecisionKind,
			&i.DecisionReason,
			&i.ItemJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChannelHealth = `-- name: ListSessionChannelHealth :many
SELECT session_id, kind, consecutive_failures, first_failure_at,
       last_failure_at, last_channel, last_error, escalated_at
FROM session_channel_health WHERE session_id = ?
`

func (q *Queries) ListSessionChannelHealth(ctx context.Context, sessionID string) ([]SessionChannelHealth, error) {
	rows, err := q.db.QueryContext(ctx, listSessionChannelHealth, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionChannelHealth
	for rows.Next() {
		var i SessionChannelHealth
		if err := rows.Scan(
			&i.SessionID,
			&i.Kind,
			&i.ConsecutiveFailures,
			&i.FirstFailureAt,
			&i.LastFailureAt,
			&i.LastChannel,
			&i.LastError,
			&i.EscalatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChannelHealthForSessions = `-- name: ListSessionChannelHealthForSessions :many
SELECT session_id, kind, consecutive_failures, first_failure_at,
       last_failure_at, last_channel, last_error, escalated_at
FROM session_channel_health WHERE session_id IN (/*SLICE:session_ids*/?)
`

func (q *Queries) ListSessionChannelHealthForSessions(ctx context.Context, sessionIds []string) ([]SessionChannelHealth, error) {
	query := listSessionChannelHealthForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionChannelHealth
	for rows.Next() {
		var i SessionChannelHealth
		if err := rows.Scan(
			&i.SessionID,
			&i.Kind,
			&i.ConsecutiveFailures,
			&i.FirstFailureAt,
			&i.LastFailureAt,
			&i.LastChannel,
			&i.LastError,
			&i.EscalatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionIDsByName = `-- name: ListSessionIDsByName :many
SELECT id FROM sessions WHERE name = ? ORDER BY created_at ASC
`

func (q *Queries) ListSessionIDsByName(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionIDsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenJudgesForSession = `-- name: ListTaskDoneWhenJudgesForSession :many
SELECT j.task_instance_id, j.leaf_id, j.action, j.reason, j.revision,
       j.judge_session, j.judge_workflow, j.relation, j.created_at
FROM task_done_when_judges j
JOIN task_instances t ON t.id = j.task_instance_id
WHERE t.session_id = ?
`

func (q *Queries) ListTaskDoneWhenJudgesForSession(ctx context.Context, sessionID string) ([]TaskDoneWhenJudge, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDoneWhenJudgesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenJudge
	for rows.Next() {
		var i TaskDoneWhenJudge
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.LeafID,
			&i.Action,
			&i.Reason,
			&i.Revision,
			&i.JudgeSession,
			&i.JudgeWorkflow,
			&i.Relation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenJudgesForSessions = `-- name: ListTaskDoneWhenJudgesForSessions :many
SELECT j.task_instance_id, j.leaf_id, j.action, j.reason, j.revision,
       j.judge_session, j.judge_workflow, j.relation, j.created_at
FROM task_done_when_judges j
JOIN task_instances t ON t.id = j.task_instance_id
WHERE t.session_id IN (/*SLICE:session_ids*/?)
`

func (q *Queries) ListTaskDoneWhenJudgesForSessions(ctx context.Context, sessionIds []string) ([]TaskDoneWhenJudge, error) {
	query := listTaskDoneWhenJudgesForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenJudge
	for rows.Next() {
		var i TaskDoneWhenJudge
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.LeafID,
			&i.Action,
			&i.Reason,
			&i.Revision,
			&i.JudgeSession,
			&i.JudgeWorkflow,
			&i.Relation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenStatesForSession = `-- name: ListTaskDoneWhenStatesForSession :many
SELECT s.task_instance_id, s.heartbeat_ticks, s.heartbeat_escalations,
       s.last_action, s.last_fingerprint, s.last_reason,
       s.last_body, s.escalated_at, s.escalate_reason
FROM task_done_when_states s
JOIN task_instances t ON t.id = s.task_instance_id
WHERE t.session_id = ?
`

func (q *Queries) ListTaskDoneWhenStatesForSession(ctx context.Context, sessionID string) ([]TaskDoneWhenState, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDoneWhenStatesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenState
	for rows.Next() {
		var i TaskDoneWhenState
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.LastAction,
			&i.LastFingerprint,
			&i.LastReason,
			&i.LastBody,
			&i.EscalatedAt,
			&i.EscalateReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenStatesForSessions = `-- name: ListTaskDoneWhenStatesForSessions :many
SELECT s.task_instance_id, s.heartbeat_ticks, s.heartbeat_escalations,
       s.last_action, s.last_fingerprint, s.last_reason,
       s.last_body, s.escalated_at, s.escalate_reason
FROM task_done_when_states s
JOIN task_instances t ON t.id = s.task_instance_id
WHERE t.session_id IN (/*SLICE:session_ids*/?)
`

func (q *Queries) ListTaskDoneWhenStatesForSessions(ctx context.Context, sessionIds []string) ([]TaskDoneWhenState, error) {
	query := listTaskDoneWhenStatesForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenState
	for rows.Next() {
		var i TaskDoneWhenState
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.LastAction,
			&i.LastFingerprint,
			&i.LastReason,
			&i.LastBody,
			&i.EscalatedAt,
			&i.EscalateReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenUnsatisfiedItemsForSession = `-- name: ListTaskDoneWhenUnsatisfiedItemsForSession :many
SELECT i.task_instance_id, i.position, i.item
FROM task_done_when_unsatisfied_items i
JOIN task_instances t ON t.id = i.task_instance_id
WHERE t.session_id = ?
ORDER BY i.task_instance_id, i.position
`

func (q *Queries) ListTaskDoneWhenUnsatisfiedItemsForSession(ctx context.Context, sessionID string) ([]TaskDoneWhenUnsatisfiedItem, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDoneWhenUnsatisfiedItemsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenUnsatisfiedItem
	for rows.Next() {
		var i TaskDoneWhenUnsatisfiedItem
		if err := rows.Scan(&i.TaskInstanceID, &i.Position, &i.Item); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDoneWhenUnsatisfiedItemsForSessions = `-- name: ListTaskDoneWhenUnsatisfiedItemsForSessions :many
SELECT i.task_instance_id, i.position, i.item
FROM task_done_when_unsatisfied_items i
JOIN task_instances t ON t.id = i.task_instance_id
WHERE t.session_id IN (/*SLICE:session_ids*/?)
ORDER BY i.task_instance_id, i.position
`

func (q *Queries) ListTaskDoneWhenUnsatisfiedItemsForSessions(ctx context.Context, sessionIds []string) ([]TaskDoneWhenUnsatisfiedItem, error) {
	query := listTaskDoneWhenUnsatisfiedItemsForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDoneWhenUnsatisfiedItem
	for rows.Next() {
		var i TaskDoneWhenUnsatisfiedItem
		if err := rows.Scan(&i.TaskInstanceID, &i.Position, &i.Item); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstanceLayersForSession = `-- name: ListTaskInstanceLayersForSession :many
SELECT l.task_instance_id, l.position, l.effect_id, l.status, l.inputs_json,
       l.locals_json, l.outputs_json, l.env_json, l.heartbeat_ticks,
       l.heartbeat_escalations, l.setup_at, l.failed_at, l.cleaned_at, l.error
FROM task_instance_layers l
JOIN task_instances t ON t.id = l.task_instance_id
WHERE t.session_id = ?
ORDER BY l.task_instance_id, l.position
`

func (q *Queries) ListTaskInstanceLayersForSession(ctx context.Context, sessionID string) ([]TaskInstanceLayer, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstanceLayersForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskInstanceLayer
	for rows.Next() {
		var i TaskInstanceLayer
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.Position,
			&i.EffectID,
			&i.Status,
			&i.InputsJson,
			&i.LocalsJson,
			&i.OutputsJson,
			&i.EnvJson,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstanceLayersForSessions = `-- name: ListTaskInstanceLayersForSessions :many
SELECT l.task_instance_id, l.position, l.effect_id, l.status, l.inputs_json,
       l.locals_json, l.outputs_json, l.env_json, l.heartbeat_ticks,
       l.heartbeat_escalations, l.setup_at, l.failed_at, l.cleaned_at, l.error
FROM task_instance_layers l
JOIN task_instances t ON t.id = l.task_instance_id
WHERE t.session_id IN (/*SLICE:session_ids*/?)
ORDER BY l.task_instance_id, l.position
`

func (q *Queries) ListTaskInstanceLayersForSessions(ctx context.Context, sessionIds []string) ([]TaskInstanceLayer, error) {
	query := listTaskInstanceLayersForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskInstanceLayer
	for rows.Next() {
		var i TaskInstanceLayer
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.Position,
			&i.EffectID,
			&i.Status,
			&i.InputsJson,
			&i.LocalsJson,
			&i.OutputsJson,
			&i.EnvJson,
			&i.HeartbeatTicks,
			&i.HeartbeatEscalations,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstances = `-- name: ListTaskInstances :many

SELECT id, session_id, instance_name, task_id, scope, status, sequence,
       resource, named, inputs_json, outputs_json, state_json,
       resource_observation_json, resource_observed_at, extra_done_when_json,
       error, setup_at, failed_at, cleaned_at, finalized_at
FROM task_instances WHERE session_id = ? ORDER BY instance_name
`

// Task instances (dynamic; Session.Tasks entries)
func (q *Queries) ListTaskInstances(ctx context.Context, sessionID string) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstances, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskInstance
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.InstanceName,
			&i.TaskID,
			&i.Scope,
			&i.Status,
			&i.Sequence,
			&i.Resource,
			&i.Named,
			&i.InputsJson,
			&i.OutputsJson,
			&i.StateJson,
			&i.ResourceObservationJson,
			&i.ResourceObservedAt,
			&i.ExtraDoneWhenJson,
			&i.Error,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesForSessions = `-- name: ListTaskInstancesForSessions :many
SELECT id, session_id, instance_name, task_id, scope, status, sequence,
       resource, named, inputs_json, outputs_json, state_json,
       resource_observation_json, resource_observed_at, extra_done_when_json,
       error, setup_at, failed_at, cleaned_at, finalized_at
FROM task_instances WHERE session_id IN (/*SLICE:session_ids*/?) ORDER BY session_id, instance_name
`

func (q *Queries) ListTaskInstancesForSessions(ctx context.Context, sessionIds []string) ([]TaskInstance, error) {
	query := listTaskInstancesForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskInstance
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.InstanceName,
			&i.TaskID,
			&i.Scope,
			&i.Status,
			&i.Sequence,
			&i.Resource,
			&i.Named,
			&i.InputsJson,
			&i.OutputsJson,
			&i.StateJson,
			&i.ResourceObservationJson,
			&i.ResourceObservedAt,
			&i.ExtraDoneWhenJson,
			&i.Error,
			&i.SetupAt,
			&i.FailedAt,
			&i.CleanedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpReservations = `-- name: ListUpReservations :many

SELECT child_session_name, parent_session_name, virtual_root, pid, reserved_at
FROM up_reservations ORDER BY child_session_name
`

// Up-slot reservations
func (q *Queries) ListUpReservations(ctx context.Context) ([]UpReservation, error) {
	rows, err := q.db.QueryContext(ctx, listUpReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpReservation
	for rows.Next() {
		var i UpReservation
		if err := rows.Scan(
			&i.ChildSessionName,
			&i.ParentSessionName,
			&i.VirtualRoot,
			&i.Pid,
			&i.ReservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSessionParentID = `-- name: LiveSessionParentID :one
SELECT parent_session_id FROM sessions WHERE id = ?
`

func (q *Queries) LiveSessionParentID(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, liveSessionParentID, id)
	var parent_session_id sql.NullString
	err := row.Scan(&parent_session_id)
	return parent_session_id, err
}

const nextEventSequence = `-- name: NextEventSequence :one

SELECT COALESCE(MAX(sequence), 0) + 1 FROM events WHERE session_id = ?
`

// Events
func (q *Queries) NextEventSequence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEventSequence, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionEverExistedByName = `-- name: SessionEverExistedByName :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE name = ?)
`

func (q *Queries) SessionEverExistedByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionEverExistedByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionIDByLiveName = `-- name: SessionIDByLiveName :one
SELECT id FROM sessions WHERE name = ? AND status <> 'destroyed'
`

func (q *Queries) SessionIDByLiveName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, sessionIDByLiveName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const sessionNameByID = `-- name: SessionNameByID :one
SELECT name FROM sessions WHERE id = ?
`

func (q *Queries) SessionNameByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, sessionNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const sessionNamesByIDs = `-- name: SessionNamesByIDs :many
SELECT id, name FROM sessions WHERE id IN (/*SLICE:ids*/?)
`

type SessionNamesByIDsRow struct {
	ID   string
	Name string
}

func (q *Queries) SessionNamesByIDs(ctx context.Context, ids []string) ([]SessionNamesByIDsRow, error) {
	query := sessionNamesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionNamesByIDsRow
	for rows.Next() {
		var i SessionNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionByID = `-- name: UpdateSessionByID :exec
UPDATE sessions SET
    name = ?,
    status = ?,
    destroyed_at = ?,
    parent_session_id = ?,
    root_session_id = ?,
    resource_id = ?,
    alias = ?,
    workflow = ?,
    workspace_dir = ?,
    population_workflow = ?,
    population_name = ?,
    inputs_json = ?,
    health_last_checked_at = ?,
    health_last_activity_at = ?,
    health_last_fingerprint = ?,
    health_last_state = ?,
    health_last_reason = ?,
    health_last_notified_at = ?,
    health_notify_count = ?,
    tick_consecutive_unchanged = ?,
    tick_last_fingerprint = ?,
    last_tick_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateSessionByIDParams struct {
	Name                     string
	Status                   string
	DestroyedAt              sql.NullString
	ParentSessionID          sql.NullString
	RootSessionID            sql.NullString
	ResourceID               sql.NullString
	Alias                    sql.NullString
	Workflow                 string
	WorkspaceDir             sql.NullString
	PopulationWorkflow       sql.NullString
	PopulationName           sql.NullString
	InputsJson               sql.NullString
	HealthLastCheckedAt      sql.NullString
	HealthLastActivityAt     sql.NullString
	HealthLastFingerprint    sql.NullString
	HealthLastState          sql.NullString
	HealthLastReason         sql.NullString
	HealthLastNotifiedAt     sql.NullString
	HealthNotifyCount        sql.NullInt64
	TickConsecutiveUnchanged sql.NullInt64
	TickLastFingerprint      sql.NullString
	LastTickAt               sql.NullString
	UpdatedAt                string
	ID                       string
}

func (q *Queries) UpdateSessionByID(ctx context.Context, arg UpdateSessionByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionByID,
		arg.Name,
		arg.Status,
		arg.DestroyedAt,
		arg.ParentSessionID,
		arg.RootSessionID,
		arg.ResourceID,
		arg.Alias,
		arg.Workflow,
		arg.WorkspaceDir,
		arg.PopulationWorkflow,
		arg.PopulationName,
		arg.InputsJson,
		arg.HealthLastCheckedAt,
		arg.HealthLastActivityAt,
		arg.HealthLastFingerprint,
		arg.HealthLastState,
		arg.HealthLastReason,
		arg.HealthLastNotifiedAt,
		arg.HealthNotifyCount,
		arg.TickConsecutiveUnchanged,
		arg.TickLastFingerprint,
		arg.LastTickAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertEventCursor = `-- name: UpsertEventCursor :exec
INSERT INTO event_cursors (session_id, kind, next_sequence) VALUES (?, ?, ?)
ON CONFLICT(session_id, kind) DO UPDATE SET next_sequence = excluded.next_sequence
`

type UpsertEventCursorParams struct {
	SessionID    string
	Kind         string
	NextSequence int64
}

func (q *Queries) UpsertEventCursor(ctx context.Context, arg UpsertEventCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventCursor, arg.SessionID, arg.Kind, arg.NextSequence)
	return err
}

const upsertPopulation = `-- name: UpsertPopulation :exec
INSERT INTO populations (workflow, name) VALUES (?, ?)
ON CONFLICT(workflow, name) DO NOTHING
`

type UpsertPopulationParams struct {
	Workflow string
	Name     string
}

func (q *Queries) UpsertPopulation(ctx context.Context, arg UpsertPopulationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPopulation, arg.Workflow, arg.Name)
	return err
}

const upsertSessionChannelHealth = `-- name: UpsertSessionChannelHealth :exec
INSERT INTO session_channel_health (
    session_id, kind, consecutive_failures, first_failure_at,
    last_failure_at, last_channel, last_error, escalated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id, kind) DO UPDATE SET
    consecutive_failures = excluded.consecutive_failures,
    first_failure_at = excluded.first_failure_at,
    last_failure_at = excluded.last_failure_at,
    last_channel = excluded.last_channel,
    last_error = excluded.last_error,
    escalated_at = excluded.escalated_at
`

type UpsertSessionChannelHealthParams struct {
	SessionID           string
	Kind                string
	ConsecutiveFailures int64
	FirstFailureAt      string
	LastFailureAt       string
	LastChannel         sql.NullString
	LastError           sql.NullString
	EscalatedAt         sql.NullString
}

func (q *Queries) UpsertSessionChannelHealth(ctx context.Context, arg UpsertSessionChannelHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionChannelHealth,
		arg.SessionID,
		arg.Kind,
		arg.ConsecutiveFailures,
		arg.FirstFailureAt,
		arg.LastFailureAt,
		arg.LastChannel,
		arg.LastError,
		arg.EscalatedAt,
	)
	return err
}

const upsertTaskInstance = `-- name: UpsertTaskInstance :one
INSERT INTO task_instances (
    id, session_id, instance_name, task_id, scope, status, sequence,
    resource, named, inputs_json, outputs_json, state_json,
    resource_observation_json, resource_observed_at, extra_done_when_json,
    error, setup_at, failed_at, cleaned_at, finalized_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id, instance_name) DO UPDATE SET
    task_id = excluded.task_id,
    scope = excluded.scope,
    status = excluded.status,
    sequence = excluded.sequence,
    resource = excluded.resource,
    named = excluded.named,
    inputs_json = excluded.inputs_json,
    outputs_json = excluded.outputs_json,
    state_json = excluded.state_json,
    resource_observation_json = excluded.resource_observation_json,
    resource_observed_at = excluded.resource_observed_at,
    extra_done_when_json = excluded.extra_done_when_json,
    error = excluded.error,
    setup_at = excluded.setup_at,
    failed_at = excluded.failed_at,
    cleaned_at = excluded.cleaned_at,
    finalized_at = excluded.finalized_at
RETURNING id
`

type UpsertTaskInstanceParams struct {
	ID                      string
	SessionID               string
	InstanceName            string
	TaskID                  string
	Scope                   string
	Status                  string
	Sequence                int64
	Resource                sql.NullString
	Named                   bool
	InputsJson              sql.NullString
	OutputsJson             sql.NullString
	StateJson               sql.NullString
	ResourceObservationJson sql.NullString
	ResourceObservedAt      sql.NullString
	ExtraDoneWhenJson       sql.NullString
	Error                   sql.NullString
	SetupAt                 sql.NullString
	FailedAt                sql.NullString
	CleanedAt               sql.NullString
	FinalizedAt             sql.NullString
}

func (q *Queries) UpsertTaskInstance(ctx context.Context, arg UpsertTaskInstanceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTaskInstance,
		arg.ID,
		arg.SessionID,
		arg.InstanceName,
		arg.TaskID,
		arg.Scope,
		arg.Status,
		arg.Sequence,
		arg.Resource,
		arg.Named,
		arg.InputsJson,
		arg.OutputsJson,
		arg.StateJson,
		arg.ResourceObservationJson,
		arg.ResourceObservedAt,
		arg.ExtraDoneWhenJson,
		arg.Error,
		arg.SetupAt,
		arg.FailedAt,
		arg.CleanedAt,
		arg.FinalizedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertUpReservation = `-- name: UpsertUpReservation :exec
INSERT INTO up_reservations (child_session_name, parent_session_name, virtual_root, pid, reserved_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(child_session_name) DO UPDATE SET
    parent_session_name = excluded.parent_session_name,
    virtual_root = excluded.virtual_root,
    pid = excluded.pid,
    reserved_at = excluded.reserved_at
`

type UpsertUpReservationParams struct {
	ChildSessionName  string
	ParentSessionName sql.NullString
	VirtualRoot       bool
	Pid               int64
	ReservedAt        string
}

func (q *Queries) UpsertUpReservation(ctx context.Context, arg UpsertUpReservationParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpReservation,
		arg.ChildSessionName,
		arg.ParentSessionName,
		arg.VirtualRoot,
		arg.Pid,
		arg.ReservedAt,
	)
	return err
}
